"""cleared

Revision ID: 865a08e116b4
Revises: c28292654a19
Create Date: 2024-05-14 18:31:24.665737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "865a08e116b4"
down_revision: Union[str, None] = "c28292654a19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("access_token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("refresh_token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("service_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="token_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="token_pkey"),
        sa.UniqueConstraint("access_token", name="token_access_token_key"),
        sa.UniqueConstraint("refresh_token", name="token_refresh_token_key"),
        sa.UniqueConstraint("user_id", name="token_user_id_key"),
    )
    # ### end Alembic commands ###
