"""remade-2

Revision ID: 4cb274a7f553
Revises: dd3ce3634ae9
Create Date: 2024-05-22 13:31:32.193405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4cb274a7f553"
down_revision: Union[str, None] = "dd3ce3634ae9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("author_login_title_idx", table_name="posts")
    op.create_index(
        "author_login_title_idx",
        "posts",
        ["author_login", "title", "deleted"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("author_login_title_idx", table_name="posts")
    op.create_index(
        "author_login_title_idx", "posts", ["author_login", "title"], unique=True
    )
    # ### end Alembic commands ###
