"""remade-1

Revision ID: dd3ce3634ae9
Revises: 4a2a2468907a
Create Date: 2024-05-21 14:25:43.375903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dd3ce3634ae9"
down_revision: Union[str, None] = "4a2a2468907a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("published_ad", sa.DateTime(), nullable=True))
    op.drop_column("posts", "published_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "published_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("posts", "published_ad")
    # ### end Alembic commands ###
